### ISSUE TITLE
No more icons in page with Shortcode (V 2.1.1)

### ISSUE THREAD

**Issue by gianky69** [katzwebservices/Wunderground#25] opened 2015-08-28 11:50 UTC
Hi, I've installed the latest version of your plugin (2.1.1) and there are no icons visualized in a page, using shortcode. It seems icons are displayed in widget.
Could you check it?
Thanks

**Comment by zackkatz** [comment] 2016-06-30 23:45
Closed - duplicate of #39 - please provide additional information there. I'm not able to reproduce.

**Closed by zackkatz** 2016-06-30 23:45 UTC
Labels: duplicate
